version: "3.9"
services:
  vault:
    image: hashicorp/vault:1.16
    container_name: vault-dev
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_ADDR=http://0.0.0.0:8200
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    command: vault server -dev -dev-root-token-id=root -dev-listen-address=0.0.0.0:8200

  app:
    build: .
    environment:
      - VAULT_ADDR=http://vault-dev:8200
      - VAULT_TOKEN=root
      - VAULT_MOUNT_KV=secret
      - VAULT_MOUNT_DB=database
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - vault

