version: "3.9"
services:
  web:
    build: .
    image: flask-template:latest
    container_name: flask-template
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: ["gunicorn", "-c", "gunicorn.conf.py", "wsgi:app"]
    restart: unless-stopped

