version: "3.9"
services:
  opa:
    image: openpolicyagent/opa:latest-debug
    command: ["run", "--server", "--log-level=debug", "--set=decision_logs.console=true", "/policies"]
    volumes:
      - ./opa/policies:/policies:ro
    ports:
      - "8181:8181"
  api:
    build:
      context: .
    environment:
      - OPA_URL=http://opa:8181
      - OPA_DECISION_PATH=infra/policy/deny
    ports:
      - "8000:8000"
    depends_on:
      - opa

